// Répertoire ROME (extrait des codes les plus courants).
// Chaque code renvoie le libellé du métier utilisé pour la recherche YouTube.
export const ROME_CODES: Record<string, string> = {
  A1101: "Conduite d'engins agricoles et forestiers",
  A1203: "Entretien des espaces verts",
  A1414: "Vente en jardinerie",
  A1416: "Polyculture, élevage",
  C1102: "Conseil clientèle en assurances",
  C1206: "Gestion de clientèle bancaire",
  D1101: "Boucherie",
  D1102: "Boulangerie - viennoiserie",
  D1103: "Charcuterie - traiteur",
  D1104: "Pâtisserie, confiserie, chocolaterie et glacerie",
  D1106: "Vente en alimentation",
  D1202: "Coiffure",
  D1208: "Soins esthétiques et corporels",
  D1211: "Vente en articles de sport et loisirs",
  D1212: "Vente en décoration et équipement du foyer",
  D1214: "Vente en habillement et accessoires de la personne",
  D1401: "Assistanat commercial",
  D1505: "Personnel de caisse",
  D1507: "Mise en rayon libre-service",
  E1103: "Communication",
  E1205: "Réalisation de contenus multimédias",
  F1601: "Application et décoration en plâtre, staff et stuc",
  F1602: "Électricité bâtiment",
  F1603: "Installation d'équipements sanitaires et thermiques",
  F1604: "Montage d'agencements",
  F1606: "Peinture en bâtiment",
  F1607: "Pose de fermetures menuisées",
  F1610: "Pose et restauration de couvertures",
  F1703: "Maçonnerie",
  F1704: "Préparation du gros œuvre et des travaux publics",
  G1601: "Management du personnel de cuisine",
  G1602: "Personnel de cuisine",
  G1603: "Personnel polyvalent en restauration",
  G1801: "Café, bar brasserie",
  G1803: "Service en restauration",
  G1703: "Réception en hôtellerie",
  H2903: "Conduite d'équipement d'usinage",
  H2913: "Soudage manuel",
  H2914: "Réalisation et contrôle de travaux d'usinage",
  H3203: "Fabrication de pièces en matériaux composites",
  I1304: "Installation et maintenance d'équipements industriels et d'exploitation",
  I1603: "Maintenance d'engins de chantier, levage, manutention et de machines agricoles",
  I1604: "Mécanique automobile et entretien de véhicules",
  J1501: "Soins d'hygiène, de confort du patient",
  J1502: "Coordination de services médicaux ou paramédicaux",
  J1506: "Soins infirmiers généralistes",
  J1301: "Personnel polyvalent des services hospitaliers",
  J1103: "Médecine généraliste et spécialisée",
  K1104: "Psychologie",
  K1207: "Intervention socioéducative",
  K1302: "Assistance auprès d'adultes",
  K1303: "Assistance auprès d'enfants",
  K1304: "Services domestiques",
  K2104: "Enseignement supérieur",
  K2111: "Formation professionnelle",
  K2204: "Nettoyage de locaux",
  K2503: "Sécurité et surveillance privées",
  M1202: "Audit et contrôle comptables et financiers",
  M1203: "Comptabilité",
  M1502: "Développement des ressources humaines",
  M1602: "Opérations administratives",
  M1607: "Secrétariat",
  M1608: "Secrétariat comptable",
  M1701: "Administration des ventes",
  M1704: "Management relation clientèle",
  M1803: "Direction des systèmes d'information",
  M1805: "Études et développement informatique",
  M1810: "Production et exploitation de systèmes d'information",
  N1101: "Conduite d'engins de déplacement des charges",
  N1103: "Magasinage et préparation de commandes",
  N1105: "Manutention manuelle de charges",
  N4101: "Conduite de transport de marchandises sur longue distance",
  N4103: "Conduite de transport en commun sur route",
  N4105: "Conduite et livraison par tournées sur courte distance",
};

export function normalizeRomeCode(input: string): string {
  return input.trim().toUpperCase().replace(/\s+/g, "");
}

export function lookupRomeLabel(input: string): string | null {
  const code = normalizeRomeCode(input);
  return ROME_CODES[code] ?? null;
}
